# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests on node 18.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build --if-present
      - name: Run ESLint
        run: npm run lint
      - name: Run Jest/RTL Tests
        run: npm test
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: chrome
          build: npm run build
          start: npm start
