# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests on node 18.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Cached node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: npm run build --if-present
        env:
          CI: false

  lint:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Cached node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint
        run: npm run lint

  tests:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Cached node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Jest/RTL Tests
        run: npm test

  cypress:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Cached node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Cypress Tests
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: chrome
          build: npm run build
          start: npm start
